# Решение практической задачи II.10.6 (ж) по курсу Вычислительной математики
#### Подготовил студент 3-го курса ФРКТ
#### Токарев Андрей

In [ ]:
import math
import matplotlib.pyplot as plt
import numpy as np

## В следующей ячейке создадим матрицу М, которая является матрицей  СЛАУ, а также введем столбец свободных членов.

In [ ]:
# Создаем матрицу СЛАУ.
M = np.array(100*[np.zeros(100)])

print("\nТаблица из \'0\' размера 100х100.\n")
print(M)
print("\n\nЗаполненная таблица!\n\n")

for k in range(100):
    M[k][k] = 20;
    if k < 4:
        for i in range(k):
            M[k][i] = 1
        for i in range(k + 1, k + 5):
            M[k][i] = 1

    if k > 3 and k < 96:
        M[k][k - 4] = 1
        M[k][k - 3] = 1
        M[k][k - 2] = 1
        M[k][k - 1] = 1
        M[k][k + 1] = 1
        M[k][k + 2] = 1
        M[k][k + 3] = 1
        M[k][k + 4] = 1
    
    if k > 95:
        for i in range(k + 1, 100):
            M[k][i] = 1
        for i in range(k - 4, k):
            M[k][i] = 1


print(M)

# Далее кусок кода, которым можно полностью вывести матрицу,
# но в ней сложно ориентироваться тогда.
#
# for row in M:
#     print(' '.join(str(col) for col in row))

# Создаем столбец свободных членов.
f = np.zeros(100)
for i in range(100):
    f[i] = i + 1

print("\n\nНиже представлен столбец свободных членов.\n\n {}".format(f))


Таблица из '0' размера 100х100.

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Заполненная таблица!


[[20.  1.  1. ...  0.  0.  0.]
 [ 1. 20.  1. ...  0.  0.  0.]
 [ 1.  1. 20. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 20.  1.  1.]
 [ 0.  0.  0. ...  1. 20.  1.]
 [ 0.  0.  0. ...  1.  1. 20.]]


Ниже представлен столбец свободных членов.

 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


Ниже напишем две функции, которые высчитывают третьи (спектральные) нормы вектора и матрицы.

In [ ]:
def NormaVector(x):
    sum = 0
    for i in x:
        sum += i**2
    return math.sqrt(sum)

def NormaMatrix(A):
    lamb, vect = np.linalg.eig(A.dot(A.T))
    max = -1000
    for i in lamb:
        if i > max:
            max = i
    return math.sqrt(math.abs(max))

# Метод Гаусса
Ниже рассмотрим решение СЛАУ методом Гаусса. 
- пройдемся по расширенной матрице прямым ходом метода Гаусса
- потом пройдемся обратным ходом и получим в итоге диагональную матрицу СЛАУ и некоторый столбец свободных членов
- получим ответ для данного метода
- выведем на печать невязки данного способа

In [ ]:
A = np.copy(M)
f1 = np.copy(f)
for k in range(100):
    a = A[k][k]
    if (99 - k) > 3:
        for i in range(1, 5):
            f1[k + i] = f1[k + i] - f1[k]*(A[k + i][k])/a
            A[k + i] = A[k + i] - A[k]*(A[k + i][k])/a
    else:
        for i in range(1, 99 - k + 1):
            f1[k + i] = f1[k + i] - f1[k]*(A[k + i][k])/a
            A[k + i] = A[k + i] - A[k]*A[k + i][k]/a
    for i in range(100):
        if A[k][i] < 10**(-15):
            A[k][i] = 0


l = list(range(100)[::-1])
for k in l:
    a = A[k][k]
    if k > 3:
        for i in range(1, 5):
            f1[k - i] = f1[k - i] - f1[k]*(A[k - i][k])/a
            A[k - i] = A[k - i] - A[k]*(A[k - i][k])/a
    else:
        for i in range(1, k + 1):
            f1[k - i] = f1[k - i] - f1[k]*(A[k - i][k])/a
            A[k - i] = A[k - i] - A[k]*(A[k - i][k])/a
    for i in range(100):
        if A[k][i] < 10**(-15):
            A[k][i] = 0

print("Вывод столбца свободных членов.\n")
print(f1)

# Далее кусок кода, которым можно полностью вывести матрицу,
# но в ней сложно ориентироваться тогда.
#
# for row in A:
#     print(' '.join(str(col) for col in row))

print("\nВывод преобразованной с помощью прямого и обратного ходов Гаусса матрицы СЛАУ.\n")
print(A)

res = np.zeros(100)

for i in range(len(res)):
    res[i] = f1[i]/(A[i][i])

print("\nВывод получившегося решения.\n")
print(res)

A = np.copy(M)
r = A.dot(res) - f
print("\nВывод невязок.\n")
print(r)

for i in range(len(r)):
    if r[i] < 10**(-15):
        r[i] = 0

print("\nВывод на печать невязок, при условии, что все числа меньше е-16 приравняны 0.\n\n {}".format(r))
print("\nНорма невязок методом Гаусса: {}".format(NormaVector(A.dot(res) - f)))

Вывод столбца свободных членов.

[ 0.50441291  1.32791161  2.1106438   2.85312639  3.55585484  4.25265667
  4.95540059  5.66215515  6.37093746  7.079728    7.78794674  8.49589894
  9.20378998  9.9117235  10.61970001 11.32768918 12.03567687 12.74365983
 13.45164028 14.15962049 14.86760113 15.57558213 16.28356323 16.99154429
 17.69952532 18.40750632 19.11548733 19.82346834 20.53144935 21.23943036
 21.94741138 22.65539239 23.3633734  24.07135441 24.77933542 25.48731644
 26.19529745 26.90327846 27.61125947 28.31924048 29.0272215  29.73520251
 30.44318352 31.15116453 31.85914554 32.56712656 33.27510757 33.98308858
 34.69106959 35.39905061 36.10703162 36.81501263 37.52299364 38.23097465
 38.93895567 39.64693668 40.35491769 41.0628987  41.77087971 42.47886073
 43.18684174 43.89482275 44.60280376 45.31078478 46.01876579 46.7267468
 47.43472781 48.14270881 48.85068983 49.55867087 50.26665194 50.97463296
 51.68261379 52.39059434 53.09857491 53.80655679 54.51454138 55.22252769
 55.9305084  56.638

# Собственные числа
Ниже рассмотрим все собственные значения нашей матрицы и выведем минимальное и максимальное из них.

In [ ]:
# Функция, для расчета и вывода собственных значений матрицы, 
# а также вывода максимального и минимального собственных значений.

# Возвращает вектор собственных значений, а также соответствующие им собственные вектора.

def EigenValues(A):
    l, v = np.linalg.eig(A)
    print(l)

    minValue = 10**6
    maxValue = -1000
    for i in l:
        if i < minValue:
            minValue = i
        if i > maxValue:
            maxValue = i

    print("\nMin lambda: {:>3}.\nMax lambda: {:>3}.".format(minValue, maxValue))

    return (l, v)

In [ ]:
# lam, vec = np.linalg.eig(M)
print("Ниже представлены все собстенные значения данной нам матрицы.\n")
lam, vec = EigenValues(M)

Ниже представлены все собстенные значения данной нам матрицы.

[27.97196298 27.88816855 27.74956237 27.55770678 27.31476023 27.02344908
 26.68703202 26.30925774 25.89431661 25.44678708 24.97157804 24.47386815
 23.95904414 23.43264035 22.90028408 22.36765549 21.84048449 21.32465711
 20.82677408 16.97951328 16.97975111 17.03492825 17.03618023 17.12575352
 17.12962304 17.24986417 17.25899967 17.40473169 20.35976312 17.4222662
 17.58804875 17.61547873 20.29926138 20.29923092 20.2635783  20.26036207
 17.79863106 20.20552855 20.20501133 17.83120504 20.12513767 20.11845058
 20.03201576 20.02531643 19.99075902 17.94490771 17.94444302 17.97197742
 17.97465875 19.9651453  19.92148358 18.0189467  18.03733413 18.02239119
 18.055217   19.79115068 19.89595662 19.88989371 19.85387501 19.7640424
 18.16104778 18.17656397 19.74217521 19.68564239 19.59098295 18.4761787
 18.25953101 18.56099279 18.58505816 18.63072054 18.65010715 18.75666047
 18.37837232 18.7775099  19.31017081 19.24376207 19.21304218 18.

In [ ]:
m = np.linalg.inv(M)

print("Ниже представлены все собвственные числа обратной матрицы.\n")
lam1, vec1 = EigenValues(m)

Ниже представлены все собвственные числа обратной матрицы.

[0.03575008 0.0358575  0.0360366  0.03628749 0.03661024 0.0370049
 0.03747138 0.03800943 0.03861851 0.03929769 0.04004553 0.04085991
 0.04173789 0.04267552 0.04366758 0.04470741 0.0588945  0.05889368
 0.05870292 0.0586986  0.05839159 0.0583784  0.04578653 0.05797147
 0.05794079 0.05745564 0.05739781 0.05685679 0.04689407 0.05676826
 0.0561841  0.04801512 0.05608146 0.05564218 0.05572756 0.05572612
 0.05563388 0.05549714 0.05548653 0.05544057 0.05538565 0.0550629
 0.0550159  0.04911649 0.05476592 0.05473803 0.05463783 0.05462731
 0.05527422 0.04926288 0.04926295 0.04934963 0.04935746 0.05441178
 0.05438244 0.05412375 0.05387643 0.05367479 0.05380667 0.05361899
 0.04949141 0.04949267 0.05331439 0.0532552  0.05315912 0.0496891
 0.04970562 0.05294312 0.05247758 0.05286999 0.05204798 0.05196489
 0.0524327  0.05178618 0.04992009 0.04993679 0.05169319 0.05230652
 0.05234476 0.05129501 0.05002311 0.05134863 0.05008729 0.05079844
 0.05

In [ ]:
# Рассчитаем число обусловленности по 3 норме.

u = NormaMatrix(m) * NormaMatrix(M)
print("Число обусловленности, путем создания функции, вычисляющей норму матрицы: u = {}.".format(u))
print("\nФункция для определения норм матрицы и вектора приведены в начале документа.")

Число обусловленности, путем создания функции, вычисляющей норму матрицы: u = 1.6473948644009413.

Функция для определения норм матрицы и вектора приведены в начале документа.


# Метод Зейделя
Делать метод Зейделя в лоб кажется мне очень сложным делом. Поэтому я применю разложение матрицы на верхне-, нижне- треугольные и диагональную.

In [ ]:
A = np.copy(M)
f1 = np.copy(f)
L = np.array(100*[np.zeros(100)])
D = np.array(100*[np.zeros(100)])
V = np.array(100*[np.zeros(100)])

for i in range(100):
    D[i][i] = 20
    for j in range(100):
        if i < j and i > j - 5:
            V[i][j] = 1
        if i > j and i < j + 5:
            L[i][j] = 1
print("Нижнетреугольная матрица.\n")
print(L)
print("\nДиагональная матрица.\n")
print(D)
print("\nВерхнетреугольная матрица.\n")
print(V)

Нижнетреугольная матрица.

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]]

Диагональная матрица.

[[20.  0.  0. ...  0.  0.  0.]
 [ 0. 20.  0. ...  0.  0.  0.]
 [ 0.  0. 20. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 20.  0.  0.]
 [ 0.  0.  0. ...  0. 20.  0.]
 [ 0.  0.  0. ...  0.  0. 20.]]

Верхнетреугольная матрица.

[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Создаем необходимые для итерационного процесса разрешающий оператор и вектор смещения.

R = (np.linalg.inv(L + D)).dot(V)*(-1)
f2 = np.linalg.inv(L + D).dot(f1)
for i in range(100):
    for j in range(100):
        if abs(R[i][j]) < 10**(-15):
            R[i][j] = 0
print("Разрешающий оператор:\n\n {}\n\nСтолбец свободных членов при переходе:\n\n {}".format(R, f2))

Разрешающий оператор:

 [[ 0.         -0.05       -0.05       ...  0.          0.
   0.        ]
 [ 0.          0.0025     -0.0475     ...  0.          0.
   0.        ]
 [ 0.          0.002375    0.004875   ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.00927469 -0.04286875
  -0.045125  ]
 [ 0.          0.          0.         ...  0.00631095  0.00927469
  -0.04286875]
 [ 0.          0.          0.         ...  0.00362041  0.00631095
   0.00927469]]

Столбец свободных членов при переходе:

 [0.05       0.0975     0.142625   0.18549375 0.22621906 0.26740811
 0.3089127  0.35059832 0.39234309 0.43403689 0.47570545 0.51736581
 0.55902744 0.60069322 0.6423604  0.68402766 0.72569456 0.76736121
 0.80902781 0.85069444 0.8923611  0.93402777 0.97569444 1.01736111
 1.05902778 1.10069444 1.14236111 1.18402778 1.22569444 1.26736111
 1.30902778 1.35069444 1.39236111 1.43402778 1.47569444 1.51736111
 1.55902778 1.60069444 1.64236111 1.68402778 1.72569444 1.767361

In [ ]:
# Функция, которая возвращает значение следующей итерации

def iterProcess(x):
    return R.dot(x) + f2

In [ ]:
print("Норма разрешающего оператора: {}".format(NormaMatrix(R)))
print("Модуль нормы разрешающего оператора: {}".format(abs(NormaMatrix(R))))

print("\nМы видим, что модуль нормы матрицы равен числу, меньшему 1, поэтому метод сходится.\n"
        "Но также метод сходится из-за того, что изначальная матрица была с диагональным преобладанием.\n")

q = abs(NormaMatrix(R))
x = np.zeros(100)
e0 = NormaVector(res)
e = 10**(-14)
s = (math.log(e) - math.log(e0))/math.log(q)
print("Число итераций, необходимое для достижения точности в {}, где точным решением выбрано решение СЛАУ по методу Гаусса: {}.\n".format(e, math.ceil(s)))

for _ in range(20):
    x = iterProcess(x)

print("\nРешение методом Гаусса:\n\n")
print(res)
print("\nРешение методом Зейделя:\n\n")
print(x)
print("\nНорма разности решений: {}".format(NormaVector(x - res)))


print("\nВывод вектора невязок для метода Зейделя:\n\n")
A = np.copy(M)
print(A.dot(x) - f)
print("\nНорма невязок методом Зейделя: {}".format(NormaVector(A.dot(x) - f)))


Норма матрицы перехода: (0.02883626683458236+0.01198846382645783j)
Модуль нормы матрицы перехода: 0.031229049775385778

Мы видим, что модуль нормы матрицы равен числу, меньшему 1, поэтому метод сходится.
Но также метод сходится из-за того, что изначальная матрица была с диагональным преобладанием.

Число итераций, необходимое для достижения точности в 1e-14, где точным решением выбрано решение СЛАУ по методу Гаусса: 11.


Решение методом Гаусса:


[0.02522065 0.06656199 0.10603713 0.14363565 0.17935233 0.21451454
 0.24997228 0.28562803 0.32138319 0.35713861 0.39286498 0.42857782
 0.46428757 0.49999946 0.53571352 0.57142822 0.60714284 0.64285722
 0.67857148 0.71428573 0.74999999 0.78571428 0.82142857 0.85714286
 0.89285714 0.92857143 0.96428571 1.         1.03571429 1.07142857
 1.10714286 1.14285714 1.17857143 1.21428571 1.25       1.28571429
 1.32142857 1.35714286 1.39285714 1.42857143 1.46428571 1.5
 1.53571429 1.57142857 1.60714286 1.64285714 1.67857143 1.71428571
 1.75       1.78571

# 24.10.2020

# г. Догопрудный